# Pipeline pour un projet Python avec Github Actions

name: Python CI
on: [push]

# Contrainte de temps de build
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: actions/checkout@v2

    # Installation de Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Validation de la qualité du code
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint devopstp.py

    # Exécution des tests
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests.py

    # Envoi de la notification par mail 
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: starting
        channel: '#github'
        message: 'Starting Build and Deploy...'
      if: always()