# Pipeline pour un projet Python avec Github Actions

name: Python CI
on: [push]

# Contrainte de temps de build
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10


    steps:
    - uses: actions/checkout@v2

    # Installation de Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Validation de la qualité du code
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint devopstp.py

    # Exécution des tests
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests.py

    # Envoi de la notification par mail 
  slack_notification:
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: 'github'
        with:
          args: |
            --title "Build ${{ job.status }}" \
            --fields branch,commit,author,commit_message \
            --commit_url "http://github.com/MyAccountDevOps/tp_repository/commit/${{ github.sha }}" \
            --color ${{ job.status == 'success' && 'good' || 'danger' }} \
            --status ${{ job.status }}